### ISSUE TITLE
Image not shown

### ISSUE THREAD

**Issue by Guangzhengzhong** [DeepInsight-AI/DeepBI#105]
The generated images are stored in HTML files and are not displayed directly
![1](https://github.com/DeepInsight-AI/DeepBI/assets/52954793/ae154d21-c7f6-4f87-919e-310691a45778)

**Comment by wangshiyouyang** [comment]
建议提问问题时添加对图形化的描述：比如 搜索次数和新客户转化率用折线图表示

**Comment by wangshiyouyang** [comment]
No reappearance

**Comment by zhouhoo** [comment]
I had the same issure, only output the LLM prograss, no chart show.
Q:  "用柱状图画出销量最高的10个城市的销量"
R: "The analyst provided a Python script to generate a bar chart showing the total sales of the top 10 cities by excluding the cities with 0 sales. The script uses Pandas and Pyecharts libraries to query data from a database table called 'order_list' and filter out the cities with 0 sales. The bar chart is rendered using Pyecharts and includes data zoom, data view, and chart type switch features.The script generates a JSON format string containing the Pyechart's chart code, which can be used to render the chart in a web page. Therefore, it's suggested that the user needs to have the required libraries installed and make sure to modify the connection details to match their environment before executing the script.In conclusion, the code provided by the analyst generates a bar chart that visually represents the total sales of the top 10 cities, excluding the cities with 0 sales. The chart provides an easy-to-understand visualization of the sales data, which can help stakeholders in making informed business decisions."

**Comment by zhouhoo** [comment]
I use openai gpt-3.5-turbo.  latested code.
