### ISSUE TITLE
openai被强制要求开启代理

### ISSUE THREAD

**Issue by stepkim1** [DeepInsight-AI/DeepBI#152]
openai设置apikey的时候强制要求配置代理地址, 海外机器不需要强制代理的话需要怎么跳过这个验证呢

**Comment by wangshiyouyang** [comment]
可以修改 安装后的 client/dist/llm.json 配置

将：
 "OpenAI": {
        "OpenaiApiKey": "",
        "HttpProxyHost": "",
        "HttpProxyPort": "",
        "ApiHost": "",
        "required": [
            "OpenaiApiKey",
            "HttpProxyHost"  // 去掉这行
    },

修改为
 "OpenAI": {
        "OpenaiApiKey": "",
        "HttpProxyHost": "",
        "HttpProxyPort": "",
        "ApiHost": "",
        "required": [
            "OpenaiApiKey"
        ]
    },
