### ISSUE TITLE
创建新用户报错

### ISSUE THREAD

**Issue by stepkim1** [DeepInsight-AI/DeepBI#154]
![image](https://github.com/user-attachments/assets/4c250d97-7d4c-49f7-8223-1b851a76ded9)
![image](https://github.com/user-attachments/assets/0bdcc65c-619f-4ca1-8d38-e9e0e2f78b1b)
### 版本
1eb87f8e710ab6a752891df1b9581bbb0bdfc07e
### 环境
2c8G   ubuntu22.04.1 
### 部署方式
docker部署

**Comment by wangshiyouyang** [comment]
Modify DeepBI/bi/templates/emails/invite.html The HTML below 30 lines change "url_for('redash.index"  to "url_for(' bi. Index '"

**Comment by stepkim1** [comment]
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/c7a643c8-b567-4651-824b-df5c9d5555af">
这个方式之前就用过了, 还是发不出邮件, 而且行数也不是一样

**Comment by stepkim1** [comment]
更新到最新版本4a20c7efc13066b2f6d040a6d93b21af740a86f0之后, 还是发不出邮件

**Comment by stepkim1** [comment]
会有toast提示:
![image](https://github.com/user-attachments/assets/982d71fd-6a73-4bd2-b6b7-507e07862e0c)
请求返回的响应是这样的:
![image](https://github.com/user-attachments/assets/64c05032-d7a9-4e27-9369-1124e86da25f)
