### ISSUE TITLE
Unexpected Internal Server Error after Redeploying without Properly Shutting Down Docker Compose Service

### ISSUE THREAD

**Issue by mattheliu** [DeepInsight-AI/DeepBI#46]
Upon redeploying a Docker Compose service without prior shutdown, an unexpected Internal Server Error is encountered in the data source.
![T0mDmA03s5](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/10fac4e9-a1b9-4b5e-8897-b5a90a688b63)

**Comment by wangshiyouyang** [comment]
If reinstalling, make sure to first stop and uninstall the previous containers  : sudo docker-compose down
