### ISSUE TITLE
Function {'task_base'} not found

### ISSUE THREAD

**Issue by LiChengxin007** [DeepInsight-AI/DeepBI#58]
<img width="856" alt="image" src="https://github.com/DeepInsight-AI/DeepBI/assets/36986406/ae943e23-1626-4afe-83b4-11f1e19e9760">

**Comment by mattheliu** [comment]
The function format called by function Call is wrong. Add a function to determine whether the called function is in the array.
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/abb05a57-26c8-45b9-999f-a45936ebb091)
