### ISSUE TITLE
Version error, not applicable

### ISSUE THREAD

**Issue by thudeng** [DeepInsight-AI/DeepBI#63]
1.2.1 exe version, error message when using the large screen module
![img_v3_0276_98b87c57-92bb-4da7-b749-002049ab861g](https://github.com/DeepInsight-AI/DeepBI/assets/145744100/594e28a6-e7c4-4349-ab4c-c1f63220ef39)

**Comment by mattheliu** [comment]
- **Reason for Closure:** [Path error under Windows]
- **Solution Implemented:** [Using os.path.join to build paths avoids errors]

If you have any further questions or concerns, please feel free to reopen the issue or open a new one. Your feedback is valuable to us, and we encourage continued collaboration.

Thank you,
[leonliuzx]
[DeepBI]

![图片](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/f113b829-5efe-4e98-ba29-efc9d86be97e)
