### ISSUE TITLE
The scale setting of the generated graph is unreasonable

### ISSUE THREAD

**Issue by thudeng** [DeepInsight-AI/DeepBI#66]
![1](https://github.com/DeepInsight-AI/DeepBI/assets/145744100/3312c304-30cf-4f10-8c8b-0dda51494b27)
The maximum value of data in the image does not exceed 0.2M, resulting in low utilization of the image and unclear differences in image data

**Comment by mattheliu** [comment]
This doesn't seem to be a bug. You can use the area selection tool to solve this problem
