### ISSUE TITLE
Data display error on the x axis when creating a histogram

### ISSUE THREAD

**Issue by ulead12** [DeepInsight-AI/DeepBI#67]
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/122712118/4e4d6ef6-3cdf-495a-8600-13a61438513f)

**Comment by mattheliu** [comment]
Thank you for addressing the issue. It seems that the problem might have been related to an SQL query error. We appreciate your effort in fixing it. If you encounter any further issues or if there's anything else we can assist you with, please feel free to let us know. Your detailed logs and feedback are invaluable in improving our system. Thanks again for your contribution!

![image](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/cfce6fa4-13b2-41f5-8c7f-96c86bda2574)
