### ISSUE TITLE
Can‘t create chart because the error in calling `bi_run_chart_code` function.

### ISSUE THREAD

**Issue by ulead12** [DeepInsight-AI/DeepBI#69]
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/122712118/1fb68f23-3930-43a8-8ffd-48028bb2360c)

**Comment by mattheliu** [comment]
The function format called by function Call is wrong. Add a function to determine whether the called function is in the array.
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/abb05a57-26c8-45b9-999f-a45936ebb091)
