### ISSUE TITLE
Unable to find data to plot

### ISSUE THREAD

**Issue by xueyou5555** [DeepInsight-AI/DeepBI#72]
Q:Which city in Beijing, Shanghai, Guangzhou, and Shenzhen is more active in terms of "virtual transaction quantity" and "virtual transaction unit price"?
Provided required fields for analysis and drawing failed, unable to find data
![011903](https://github.com/DeepInsight-AI/DeepBI/assets/112793316/db9b4dcc-0ff2-47ac-a1dc-4f1138c61e8e)

**Comment by mattheliu** [comment]
Reason for Closure: [Data field value is Chinese]
    Solution Implemented: [Correct after modifying comment]

If you have any further questions or concerns, please feel free to reopen the issue or open a new one. Your feedback is valuable to us, and we encourage continued collaboration.

Thank you,
[leonliuzx]
[DeepBI]
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/056e7710-1c69-4f0b-8f02-cc3032ae379c)
