### ISSUE TITLE
Semantic expressions make it impossible to draw pictures

### ISSUE THREAD

**Issue by xueyou5555** [DeepInsight-AI/DeepBI#77]
Q：Draw a funnel based on clicks, favorites, add-ons, and payments data in the transaction data and analyze it
Can't draw a picture by asking this question
![20240123Q27_01](https://github.com/DeepInsight-AI/DeepBI/assets/112793316/80f0ea49-dc1b-4c32-9d7d-4a4b31f0afcd)

Q：Based on the clicks, favorites, add-ons, and payment data in the transaction data, it is represented and analyzed by a funnel chart
Can draw a picture with this question
![20240123Q27_02](https://github.com/DeepInsight-AI/DeepBI/assets/112793316/258fdeda-bccd-477f-978d-236b8019e5a0)

Draw a funnel based on clicks, favorites, add-ons, and payments data in the transaction data and analyze it
Can draw a picture by asking a question in English
![20240123Q27_03](https://github.com/DeepInsight-AI/DeepBI/assets/112793316/6ec57803-b74a-4fca-aad9-506ff8399528)

**Comment by mattheliu** [comment]
The function format called by function Call is wrong. Add a function to determine whether the called function is in the array.
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/abb05a57-26c8-45b9-999f-a45936ebb091)
![image](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/7ecf4abe-afad-4634-ad5f-60a78ca7eddf)
