### ISSUE TITLE
There is a problem with drawing pictures for months and quarters

### ISSUE THREAD

**Issue by xueyou5555** [DeepInsight-AI/DeepBI#80]
Q:How does spending behavior differ from month to month? Analyze it visually
![20240123Q42_01](https://github.com/DeepInsight-AI/DeepBI/assets/112793316/ec72726c-f14a-4a8e-9258-33c20681f8d9)

Q:How does consumer behavior differ from quarter to quarter? Analyze it visually
![20240123Q42_02](https://github.com/DeepInsight-AI/DeepBI/assets/112793316/708f1cec-b5ae-403d-bf50-6aae5358b99e)

There is no problem with the quarter drawing, but there is an error when drawing the month

**Comment by mattheliu** [comment]
- Reason for Closure: [query using %%Y-%%M, MYSQL cannot recognize it]
    - Solution Implemented: [query using %Y-%M]

If you have any further questions or concerns, please feel free to reopen the issue or open a new one. Your feedback is valuable to us, and we encourage continued collaboration.

Thank you,
[leonliuzx]
[DeepBI]

![image](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/454d7fb7-01cb-41db-9a2b-741706816ddd)
![image](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/40abf5f2-eecc-4940-8609-d1d17cd617b2)
