### ISSUE TITLE
Error: Function {'task_base'} not found

### ISSUE THREAD

**Issue by ulead12** [DeepInsight-AI/DeepBI#83]
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/122712118/62cf5813-7f16-410d-9209-7fd055bedc8c)
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/122712118/cb94ceba-c8ea-4ce2-9809-0c1ecb249536)

**Comment by mattheliu** [comment]
The function format called by function Call is wrong. Add a function to determine whether the called function is in the array.
![图片](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/abb05a57-26c8-45b9-999f-a45936ebb091)
