### ISSUE TITLE
  Designing multi category drawings in reports can lead to errors

### ISSUE THREAD

**Issue by xueyou5555** [DeepInsight-AI/DeepBI#85]
(Report dialogue) Use a bar chart to represent the cumulative number of patent applications and authorizations in Beijing, Shanghai, Guangzhou, and Shenzhen each year
![20240130Q46](https://github.com/DeepInsight-AI/DeepBI/assets/112793316/873377b1-9023-4364-9830-2d3d3d5ffc51)

**Comment by mattheliu** [comment]
- Reason for Closure: [Value used as classification is not defined in json]
    - Solution Implemented: [The value defined in json to be used as a classification series']

If you have any further questions or concerns, please feel free to reopen the issue or open a new one. Your feedback is valuable to us, and we encourage continued collaboration.

Thank you,
[leonliuzx]
[DeepBI]

![fc218c35-d75d-437b-aeb7-aa8634c68c16](https://github.com/DeepInsight-AI/DeepBI/assets/102272920/e2a3582f-dfb7-4a62-8e5e-6e3e7a2fbc68)
